#lang racket

(require 2htdp/image)
(provide make-car)
(provide make-ball)
(provide car-width)
(provide car-length)

(define car-width 100)
(define car-length 50)

(define (make-car pos theta name color)
  (let ((image (overlay/align "right" "middle" (rectangle (/ car-width 5) car-length "solid" "black")(rectangle car-width car-length "solid" color)))
        (velocity '(0 0))
        (boost 0)
        (acc #f))
    (define (update-c lst)
      (set! pos (car lst))
      (set! velocity (cadr lst))
      (set! theta (caddr lst)))
    (define (set-acc bool)
      (set! acc bool))
    (define (dispatch m)
      (cond ((eq? m 'get-x) (car pos))
            ((eq? m 'get-y) (cadr pos))
            ((eq? m 'get-pos) pos)
            ((eq? m 'get-velo) velocity)
            ((eq? m 'update-car) update-c)
            ((eq? m 'get-theta) theta)
            ((eq? m 'get-image) (rotate theta image))
            ((eq? m 'get-name) name)
            ((eq? m 'set-acc) set-acc) #|True is car is accelerating|#
            ((eq? m 'get-acc) acc)
            (else "wat")))
    dispatch))

(define (make-ball pos radius)
  (let ((image (circle radius "solid" "black"))
        (velocity '(0 0)))
    (define (update-b lst)
      (set! pos (car lst))
      (set! velocity (cadr lst)))
    (define (dispatch m)
      (cond ((eq? m 'get-x) (car pos))
            ((eq? m 'get-y) (cadr pos))
            ((eq? m 'get-pos) pos)
            ((eq? m 'get-velo) velocity)
            ((eq? m 'update-ball) update-b)
            ((eq? m 'get-image) image)
            (else "wat")))
    dispatch))
    
