#lang racket

(provide make-car)
(provide make-ball)

(require 2htdp/image)
(provide make-car)
(provide make-ball)
(provide make-boost)
(provide car-width)
(provide car-length)

(define car-width 100)
(define car-length 50)

(define (make-car pos theta name color)
  (let ((image (overlay/align "right" "middle" (rectangle (/ car-width 5) car-length "solid" "black")(rectangle car-width car-length "solid" color)))
        (velocity '(0 0))
        (boost 0)
        (accelerating #f)
        (decelerating #f))
    (define (update-c lst)
      (set! pos (car lst))
      (set! velocity (cadr lst))
      (set! theta (caddr lst)))
    (define (dispatch m)
      (cond ((eq? m 'get-x) (car pos))
            ((eq? m 'get-y) (cadr pos))
            ((eq? m 'get-pos) pos)
            ((eq? m 'get-velo) velocity)
            ((eq? m 'update-car) update-c)
            ((eq? m 'get-theta) theta)
            ((eq? m 'get-image) (rotate theta image))
            ((eq? m 'get-name) name)
            ((eq? m 'active?) #t)
            ((eq? m 'accel?) accelerating)
            ((eq? m 'set-accel) (lambda (n) (set! accelerating n)))
            ((eq? m 'decel?) decelerating)
            ((eq? m 'set-decel) (lambda (n) (set! decelerating n)))
            (else "Invalid message passed to car object.")))
    dispatch))

(define (make-ball pos radius)
  (let ((image (circle radius "solid" "black"))
        (velocity '(0 0)))
    (define (update-b lst)
      (set! pos (car lst))
      (set! velocity (cadr lst)))
    (define (dispatch m)
      (cond ((eq? m 'get-x) (car pos))
            ((eq? m 'get-y) (cadr pos))
            ((eq? m 'get-pos) pos)
            ((eq? m 'get-velo) velocity)
            ((eq? m 'get-radius) radius)
            ((eq? m 'update-ball) update-b)
            ((eq? m 'get-image) image)
            ((eq? m 'active?) #t)
            (else "Invalid message passed to ball object.")))
    dispatch))
    
(define (make-boost pos)
  (let ((image (circle 20 "solid" "yellow"))
        (active #t)
        (recharge-time 0))
    (define (dispatch m)
      (cond ((eq? m 'get-x) (car pos))
            ((eq? m 'get-y) (cadr pos))
            ((eq? m 'get-pos) pos)
            ((eq? m 'get-radius) 20)
            ((eq? m 'active?) active)
            ((eq? m 'get-image) image)
            ((eq? m 'deactivate) (set! active #f) (set! recharge-time 10))
            ((eq? m 'refresh) (if (= recharge-time 0)
                                  (set! active #t)
                                  (set! recharge-time (- recharge-time 1))))
            (else "Invalid message passed to boost object.")))
    dispatch))