#lang racket

(require rsound)

(define (sound-effects)
  (let ((sound-stream (make-pstream)))
    (define (goal-scored-sound)
      (let ((goal-sound (rs-read "../../Resources/SoundEffects/goal.wav")))
        (pstream-play sound-stream goal-sound)))
    (define (engine procedure)
      (cond ((eq? procedure 'goal-scored-sound) (goal-scored-sound))
            (else (error "Unknown Sound Effect Option"))))
    engine))

(define (music-effects)
  (let ((music-stream (make-pstream)))
    (define (play-menu-music)
      (let ((menu-music (rs-read "../../Resources/MusicEffects/menu.wav")))
        (pstream-play music-stream menu-music)))
    (define (engine procedure)
      (cond ((eq? procedure 'play-menu-music) (play-menu-music))
            (else (error "Unknown Music Effect Option"))))
    engine))

(define (sound-engine)
  (let ((sound-effects-engine (sound-effects))
        (music-effects-engine (music-effects)))
    (define (play-sound-effect sound-name)
      (sound-effects-engine sound-name))
    (define (play-music-effect music-name)
      (music-effects-engine music-name))
    (define (engine procedure)
      (cond ((eq? procedure 'play-sound-effect) play-sound-effect)
            ((eq? procedure 'play-music-effect) play-music-effect)
            (else (error "Uknown Sound Engine Option"))))
    engine))